/*! Versions generated by sVersion on 2018-11-25 14:22 */
/*! \note this generated file should NOT be added to Git repository, include in .gitignore to avoid */
#ifndef AUTOVERSION_H
#define AUTOVERSION_H

#include "C_defs.h"

#define SLEEP_SENSORS_VERSION_MAJOR          ( 1u )
#define SLEEP_SENSORS_VERSION_PATCH          ( 1u )
#define SLEEP_SENSORS_VERSION_VERIFICATION   ( 0u )
#define SLEEP_SENSORS_VERSION_RELEASE_TYPE   ( SEL_ALPHA_RELEASE )
#define SLEEP_SENSORS_BUILD_ID               ( 0 )

#endif