/*! Versions generated by sVersion on 2021-05-28 17:47 */
/*! \note this generated file should NOT be added to Git repository, include in .gitignore to avoid */
#ifndef AUTOVERSION_H
#define AUTOVERSION_H

#include "C_defs.h"

#define SLEEPY_SENSOR_VERSION_MAJOR          ( 1u )
#define SLEEPY_SENSOR_VERSION_PATCH          ( 1u )
#define SLEEPY_SENSOR_VERSION_VERIFICATION   ( 0u )
#define SLEEPY_SENSOR_VERSION_RELEASE_TYPE   ( SEL_ALPHA_RELEASE )
#define SLEEPY_SENSOR_BUILD_ID               ( 0 )

#define SLEEPY_SENSOR_BUILD_DATE  ( 28u )
#define SLEEPY_SENSOR_BUILD_MONTH ( 5u )
#define SLEEPY_SENSOR_BUILD_YEAR  ( 21u )
#endif